const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg",
      id: 968051,
      title: "The Nun II",
      original_language: "en",
      original_title: "The Nun II",
      overview:
        "In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
      poster_path: "/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
      media_type: "movie",
      genre_ids: [27, 9648, 53],
      popularity: 5953.02,
      release_date: "2023-09-06",
      video: false,
      vote_average: 6.976,
      vote_count: 743,
    },
    {
      adult: false,
      backdrop_path: "/cHNqobjzfLj88lpIYqkZpecwQEC.jpg",
      id: 926393,
      title: "The Equalizer 3",
      original_language: "en",
      original_title: "The Equalizer 3",
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
      media_type: "movie",
      genre_ids: [28, 53, 80],
      popularity: 2686.985,
      release_date: "2023-08-30",
      video: false,
      vote_average: 7.333,
      vote_count: 585,
    },
    {
      adult: false,
      backdrop_path: "/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg",
      id: 84958,
      name: "Loki",
      original_language: "en",
      original_name: "Loki",
      overview:
        "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
      poster_path: "/voHUmluYmKyleFkTu3lOXQG702u.jpg",
      media_type: "tv",
      genre_ids: [18, 10765],
      popularity: 1561.465,
      first_air_date: "2021-06-09",
      vote_average: 8.16,
      vote_count: 10203,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/mzlZAMjE2yk2sW3f9HTeBM3B3jw.jpg",
      id: 616747,
      title: "Haunted Mansion",
      original_language: "en",
      original_title: "Haunted Mansion",
      overview:
        "A woman and her son enlist a motley crew of so-called spiritual experts to help rid their home of supernatural squatters.",
      poster_path: "/8Im6DknDVxRiGXc5t8rVOJyzuNx.jpg",
      media_type: "movie",
      genre_ids: [14, 35],
      popularity: 736.523,
      release_date: "2023-07-26",
      video: false,
      vote_average: 6.8,
      vote_count: 356,
    },
    {
      adult: false,
      backdrop_path: "/4DxHcIQfw3ungfQVqupJ8K62M3d.jpg",
      id: 72710,
      name: "The Continental: From the World of John Wick",
      original_language: "en",
      original_name: "The Continental: From the World of John Wick",
      overview:
        "Winston Scott is roped into a world of assassins and must make things right after his brother's attack on the Continental hotel.",
      poster_path: "/weszIbxgvh5Xnm8y76gahL3t5uL.jpg",
      media_type: "tv",
      genre_ids: [80, 10759],
      popularity: 943.153,
      first_air_date: "2023-09-22",
      vote_average: 7.879,
      vote_count: 157,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg",
      id: 980489,
      title: "Gran Turismo",
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.",
      poster_path: "/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
      media_type: "movie",
      genre_ids: [12, 28, 18],
      popularity: 2590.009,
      release_date: "2023-08-09",
      video: false,
      vote_average: 8.041,
      vote_count: 920,
    },
    {
      adult: false,
      backdrop_path: "/mvoW41kdSxiobGZ9ONL1Tqrpt3h.jpg",
      id: 114461,
      name: "Ahsoka",
      original_language: "en",
      original_name: "Ahsoka",
      overview:
        "Former Jedi Knight Ahsoka Tano investigates an emerging threat to a vulnerable galaxy.",
      poster_path: "/laCJxobHoPVaLQTKxc14Y2zV64J.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759],
      popularity: 690.896,
      first_air_date: "2023-08-22",
      vote_average: 7.84,
      vote_count: 394,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/1syW9SNna38rSl9fnXwc9fP7POW.jpg",
      id: 565770,
      title: "Blue Beetle",
      original_language: "en",
      original_title: "Blue Beetle",
      overview:
        "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.",
      poster_path: "/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
      media_type: "movie",
      genre_ids: [28, 878, 12],
      popularity: 2211.475,
      release_date: "2023-08-16",
      video: false,
      vote_average: 7.087,
      vote_count: 1202,
    },
    {
      adult: false,
      backdrop_path: "/aY7zv2pfk9H0QxaaL3PBjvalbKQ.jpg",
      id: 96677,
      name: "Lupin",
      original_language: "fr",
      original_name: "Lupin",
      overview:
        "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.",
      poster_path: "/h6Z2oogE4mJk2uffdtIlLhb0EHx.jpg",
      media_type: "tv",
      genre_ids: [80, 18, 9648],
      popularity: 832.901,
      first_air_date: "2021-01-08",
      vote_average: 7.77,
      vote_count: 1845,
      origin_country: ["FR"],
    },
    {
      adult: false,
      backdrop_path: "/aCROH2L1yTeRe3im0XOYiUbI2YJ.jpg",
      id: 205715,
      name: "Gen V",
      original_language: "en",
      original_name: "Gen V",
      overview:
        "At America's only college for superheroes, gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When the school's dark secrets come to light, they must decide what kind of heroes they want to become.",
      poster_path: "/uuot1N5AgZ7xRCKgm4ZCwOhgIJu.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 1096.175,
      first_air_date: "2023-09-28",
      vote_average: 8.071,
      vote_count: 106,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      id: 346698,
      title: "Barbie",
      original_language: "en",
      original_title: "Barbie",
      overview:
        "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
      poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
      media_type: "movie",
      genre_ids: [35, 12, 14],
      popularity: 1115.152,
      release_date: "2023-07-19",
      video: false,
      vote_average: 7.255,
      vote_count: 5275,
    },
    {
      adult: false,
      backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
      id: 575264,
      title: "Mission: Impossible - Dead Reckoning Part One",
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
      media_type: "movie",
      genre_ids: [28, 53],
      popularity: 490.319,
      release_date: "2023-07-08",
      video: false,
      vote_average: 7.7,
      vote_count: 1236,
    },
    {
      adult: false,
      backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      id: 678512,
      title: "Sound of Freedom",
      original_language: "en",
      original_title: "Sound of Freedom",
      overview:
        "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
      poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
      media_type: "movie",
      genre_ids: [28, 18],
      popularity: 3510.312,
      release_date: "2023-07-03",
      video: false,
      vote_average: 8.081,
      vote_count: 748,
    },
    {
      adult: false,
      backdrop_path: "/xvzxqKWltnj6qSiWBXRq6ZCdcrw.jpg",
      id: 1151534,
      title: "Nowhere",
      original_language: "es",
      original_title: "Nowhere",
      overview:
        "A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to the child while lost at sea, where she must fight to survive.",
      poster_path: "/rpzFxv78UvYG5yQba2soO5mMl4T.jpg",
      media_type: "movie",
      genre_ids: [53, 18],
      popularity: 1501.805,
      release_date: "2023-09-29",
      video: false,
      vote_average: 7.807,
      vote_count: 458,
    },
    {
      adult: false,
      backdrop_path: "/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg",
      id: 670292,
      title: "The Creator",
      original_language: "en",
      original_title: "The Creator",
      overview:
        "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
      poster_path: "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
      media_type: "movie",
      genre_ids: [878, 28, 53, 10752],
      popularity: 371.341,
      release_date: "2023-09-27",
      video: false,
      vote_average: 7.205,
      vote_count: 298,
    },
    {
      adult: false,
      backdrop_path: "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
      id: 1008042,
      title: "Talk to Me",
      original_language: "en",
      original_title: "Talk to Me",
      overview:
        "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
      poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      media_type: "movie",
      genre_ids: [27, 53],
      popularity: 2277.741,
      release_date: "2023-07-26",
      video: false,
      vote_average: 7.255,
      vote_count: 1151,
    },
    {
      adult: false,
      backdrop_path: "/qjMDwBWbG5hAP43q3meplZFreFQ.jpg",
      id: 974931,
      title: "Totally Killer",
      original_language: "en",
      original_title: "Totally Killer",
      overview:
        'When the infamous "Sweet Sixteen Killer" returns 35 years after his first murder spree to claim another victim, 17-year-old Jamie accidentally travels back in time to 1987, determined to stop the killer before he can start.',
      poster_path: "/52YBwGJ3cJs54fpBzwnT1lnqgTo.jpg",
      media_type: "movie",
      genre_ids: [27, 35],
      popularity: 87.206,
      release_date: "2023-09-28",
      video: false,
      vote_average: 7.159,
      vote_count: 107,
    },
    {
      adult: false,
      backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
      id: 951491,
      title: "Saw X",
      original_language: "en",
      original_title: "Saw X",
      overview:
        "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
      poster_path: "/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
      media_type: "movie",
      genre_ids: [27, 53],
      popularity: 938.895,
      release_date: "2023-09-26",
      video: false,
      vote_average: 7.2,
      vote_count: 115,
    },
    {
      adult: false,
      backdrop_path: "/a6ptrTUH1c5OdWanjyYtAkOuYD0.jpg",
      id: 37854,
      name: "One Piece",
      original_language: "ja",
      original_name: "ワンピース",
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: "/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
      media_type: "tv",
      genre_ids: [10759, 35, 16],
      popularity: 103.451,
      first_air_date: "1999-10-20",
      vote_average: 8.724,
      vote_count: 4060,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/vsrYscw6M5g1OEPxll9QTy6C9IK.jpg",
      id: 830764,
      title: "Pet Sematary: Bloodlines",
      original_language: "en",
      original_title: "Pet Sematary: Bloodlines",
      overview:
        "In 1969, a young Jud Crandall has dreams of leaving his hometown of Ludlow, Maine behind, but soon discovers sinister secrets buried within and is forced to confront a dark family history that will forever keep him connected to Ludlow.",
      poster_path: "/yqnNLn24shYnZ6kqGpbwuB3NJ0D.jpg",
      media_type: "movie",
      genre_ids: [27, 14],
      popularity: 53.425,
      release_date: "2023-09-23",
      video: false,
      vote_average: 6.6,
      vote_count: 54,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export default data;